---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error
    volumes:
      - /srv/docker/deluge:/config
      - /srv/downloads:/downloads
    restart: unless-stopped
