version: '3'
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error
    volumes:
      - /srv/docker/deluge:/config
      - /srv/downloads:/downloads
    restart: unless-stopped

  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/emby:/config
      - /srv/media/tv:/data/tvshows
      - /srv/media/movies:/data/movies
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - /srv/docker/jackett/config:/config
      - /srv/docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "${PROXYMANAGER_PASSWORD}"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /srv/docker/nginx_proxy_manager/data:/data
      - /srv/docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt

  proxy-manager-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: proxy-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: "${PROXYMANAGER_PASSWORD}"
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: "${PROXYMANAGER_PASSWORD}"
    volumes:
      - /srv/docker/nginx_proxy_manager/mysql:/var/lib/mysql

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/radarr:/config
      - /srv/media/movies:/movies
      - /srv/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

    samba:
      image: dperson/samba
      container_name: samba
      volumes:
        - /srv:/srv
      ports:
        - 139:139
        - 445:445
      command: '-s "${SAMBA_SHARENAME};</PATH/TO/DIR>;no;no;no;${SAMBA_USERNAME}" -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}"'

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/sonarr:/config
      - /srv/media/tv:/tv
      - /srv/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
