version: '3.4'
services:

  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
    environment:
      - APP_KEY=${FIREFLY_API} # must be 32 chars long
      - DB_CONNECTION=mysql
      - DB_HOST=firefly_db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=${FIREFLY_DB_PASSWORD}
    volumes:
      - /srv/docker/firefly/app:/var/www/html/storage/upload
    ports:
      - 8080:8080
    depends_on:
      - firefly_db

  firefly_db:
    image: mariadb
    container_name: firefly_db
    hostname: firefly_db
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=${FIREFLY_DB_PASSWORD}
      - MYSQL_DATABASE=firefly
    volumes:
      - /srv/docker/firefly/db:/var/lib/mysql

  firefly_importer:
    image: fireflyiii/data-importer:latest
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - firefly

  photoview_db:
    image: mariadb:10.5
    container_name: photoview_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=${PHOTOVIEW_SECRET}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - photoview_db_data:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:latest
    container_name: photoview
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      - photoview_db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:${PHOTOVIEW_SECRET}@tcp(photoview_db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    volumes:
      - photoview_api_cache:/app/cache
      - /users/steve/pictures/:/photos/steve:ro
      - /users/miki/photos/:/photos/miki:ro

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /srv/docker/nginx_proxy_manager/data:/data
      - /srv/docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=0 # Setting this as 0 is a potential security risk but nessercary with greyhole smb. THIS IS NOT RECOMMENDED
      - PGID=0 # Setting this as 0 is a potential security risk but nessercary with greyhole smb. THIS IS NOT RECOMMENDED
      - TZ=Europe/London
    volumes:
      - /srv/docker/syncthing:/config
      - /users:/data/users
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 19 * * SUN
      - WATCHTOWER_TIMEOUT=1800s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  wyl:
    image: aceberg/watchyourlan:latest
    container_name: wyl
    hostname: wyl
    environment:
      - IFACE=eth0
      - TZ=Europe/London
      - THEME=darkly
      - GUIIP=${GUIIP}
      - GUIPORT=8840
    volumes:
      - /srv/docker/wyl:/data
    network_mode: 'host'
    restart: unless-stopped

volumes:
  photoview_db_data:
  photoview_api_cache:
